name: SDK Build
on:
  workflow_call:
  workflow_dispatch:
permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: dais-technology
          repo: javascript-sdk-minimal
          github_token: ${{ secrets.DAIS_DEVOPS_TEAM_ACTIONS_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          wait_workflow: false
          ref: master
