name: rust-build
on:
  workflow_call:
    inputs:
      aws-role-to-assum:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      dais-machine-github-username:
        required: true
      dais-machine-github-email:
        required: true
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    if: github.actor != 'dais-machine'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}
          fetch-depth: 0
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.8.6'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.aws-role-to-assum }}
          aws-region: us-west-2
          role-session-name: AWSSession
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Cargo Build
        shell: bash
        run: |
          gitLog=$(git log -1 --pretty=%B | sed s/\'/\"/ | sed s/\"/\'/ | sed s/'→'/'->'/)
          git config user.name ${{ secrets.dais-machine-github-username }}
          git config user.email ${{ secrets.dais-machine-github-email }}
          
          PROJECT_NAME='${{ inputs.project-name }}'
          
          # Compile and Test
          docker build -t rust-builder -f Dockerfile.builder .
          docker run --privileged -t -d --rm --name rust-builder rust-builder
          docker exec -w /build rust-builder cargo tarpaulin --ignore-tests -vo Xml
          docker cp rust-builder:/build/cobertura.xml .
          
          # Version
          docker exec rust-builder cargo bump
          docker cp rust-builder:/build/Cargo.toml ./Cargo.toml
          nextVersion=$(awk '/^\[.*\]$/{obj=$0}/=/{print obj $0}' Cargo.toml | grep '\[package\]version = ' | awk '{print $3}' | tr -d '"' )
          
          # Build Final Image
          docker exec rust-builder cargo build --release
          docker cp rust-builder:/build/target/release/$PROJECT_NAME .
          strip --strip-all $PROJECT_NAME
          docker build -t $PROJECT_NAME -f Dockerfile.deploy .
          docker rm -f rust-builder
          
          # Release
          git commit -a -m 'Bump version in Cargo.toml for next release'
          git tag -a ${nextVersion} -m "Release ${nextVersion}"
          git push --follow-tags
          docker tag $PROJECT_NAME ${{ inputs.aws-ecr-us-west-2-registry }}/$PROJECT_NAME:$nextVersion
          docker push ${{ inputs.aws-ecr-us-west-2-registry }}/$PROJECT_NAME:$nextVersion
          echo "::set-output name=projectVersion::$PROJECT_NAME"
          echo "::set-output name=projectName::$nextVersion"
          echo "::set-output name=gitLog::$gitLog"
      - name: Push values.yaml to DAIS s3
        run: |
          cat values.yaml > values-${{ steps.read_version.outputs.build-version }}.yaml
          echo 'image: ' >> values-${{ steps.read_version.outputs.build-version }}.yaml
          echo '   repository: '991853876083.dkr.ecr.us-west-2.amazonaws.com/${{ steps.read_project_name.outputs.rootProject-name }} >> values-${{ steps.read_version.outputs.build-version }}.yaml
          echo '   pullPolicy: 'Always >> values-${{ steps.read_version.outputs.build-version }}.yaml
          echo '   tag: '${{ steps.read_version.outputs.build-version }} >> values-${{ steps.read_version.outputs.build-version }}.yaml          
          aws s3 cp values-${{ steps.read_version.outputs.build-version }}.yaml s3://dais-helm-charts/packagevalues/${{ steps.read_project_name.outputs.rootProject-name }}/values-${{ steps.read_version.outputs.build-version }}.yaml
          sed -i -e 's/all-dais-com-tls/all-dais-jm-com-tls/; s/dais.com/dais-jm.com/;' values-${projectVersion}.yaml
          aws s3 cp values-${projectVersion}.yaml s3://jm-helm-charts/packagevalues/${projectName}/values-${projectVersion}.yaml
        with:
          AWS_REGION: ${{ secrets.ACTIONS_AWS_REGION }}
      - name: Deploy To Dev
        id: deploy-to-dev
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.ACTIONS_AWS_REGION }}
          FunctionName: spinnaker-trigger-dev-deployer
          Payload: '{"application": "${{ steps.bash.outputs.projectName }}", "tag": "${{ steps.bash.outputs.projectVersion }}", "gitLog": "${{ steps.bash.outputs.gitLog }}", "repositoryName": "${{ github.repository }}"}'
